[C++23] Fix for unique_ptr issue
C++23 changed unique_ptr to a constexpr so you need the type to be
completely defined before you pass it to unique_ptr. I fixed this
incomplete type for UpdaterRuntimeInterface by adding
updater_interface.h that defines the class.

Error:
prebuilts/clang/host/linux-x86/clang-r584948/include/c++/v1/__memory/unique_ptr.h:75:19:
error: invalid application of 'sizeof' to an incomplete type
'UpdaterRuntimeInterface'
   75 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete
type");

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libupdater_core
Change-Id: I91a888a8a7a8b77f3cecafe4e537ab8c6eb3983e